version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=prisma_pg
      - POSTGRES_PASSWORD=benchmark
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${PG_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://db:${PG_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    stdin_open: true
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - db
    # v2 
    # condition: service_healthy
    # links: 
    #   - db

    ports:
      - "3040:3000"

volumes:
  postgres: