version: '3'

services:
  pgdb:
    container_name: pgdb
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5443:5432'

  # prisma:
  #   build: .
  #   container_name: prisma
  #   restart: on-failure
  #   depends_on:
  #     - pg-db
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '3000:3000'
  #   # Use the script as the entrypoint and pass the host and port of the service to wait for
  #   # entrypoint: ["/bin/sh","-c","/usr/local/bin/wait-for-it.sh", "pg-db:5432", "--"]
  #   # Use the original command of the app as an argument to the script
  #   command: ["yarn", "start"]

volumes:
  postgres: