version: '3'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 2s

  app:
    build: .
    depends_on:
      - db
        # condition: service_healthy
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: ["yarn", "start:migrate"]

volumes:
  postgres: