#first stop the docker and remove the containers:
#docker stop $(docker ps -a -q)
#docker rm $(docker ps -a -q)

version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://db:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
    build:
      context: ./
      # additional_contexts:
      #   dataPath: ../dataset
      dockerfile: Dockerfile

  server:
    stdin_open: true
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      db:
        condition: service_started
    ports:
      - "3050:3000"

volumes:
  postgres: